#server:
#  port: 9003
#  servlet:
#    context-path: /demo_spring_cloud_alibaba/user
#spring:
#  application:
#    name: User
#  profiles:
#    active: dev
#mybatis-plus:
#  mapper-location: classpath:mapper/*.xml
