#server:
#  port: 9000
#  servlet:
#    context-path: /demo_spring_cloud_alibaba/product
#spring:
#  application:
#    name: Product
#  profiles:
#    active: dev
#mybatis-plus:
#  mapper-location: classpath:mapper/*.xml
