#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        namespace: ed2069f3-cc54-4a62-b044-95061643ae84
#        group: MY_GROUP
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
#
#  datasource:
#    url: jdbc:mysql://192.168.31.100:3306/demo_spring_cloud_alibaba?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
#    username: root
#    password: mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
## 设置 feign 客户端超时时间(OpenFeign 默认支持 Ribbon)
#ribbon:
#  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#  read-timeout: 2000
#  # 指的是建立连接后从服务器读取到可用资源所用的时间
#  connect-timeout: 2000
#
#feign:
#  client:
#    config:
#      # NONE: 不记录任何日志，是OpenFeign默认日志级别（性能最佳，适用于生产环境）。
#      # BASIC: 仅记录请求方法、URL、响应状态码、执行时间（适用于生产环境追踪问题）。
#      # HEADERS: 在记录BASIC级别的基础上，记录请求和响应的header头部信息。
#      # FULL: 记录请求响应的header、body 和 元数据（适用于开发和测试环境定位问题）。
#      Product:
#        loggerLevel: full
#      Order:
#        loggerLevel: full
#logging:
#  level:
#    # Feign 调试日志是 debug 级别输出，SpringBoot 默认日志级别是 info，所以 Feign 的 debug 日志级别就不会输出
#    com.example.order.ms: debug