#server:
#  port: 9020
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
#
#  datasource:
#    url: jdbc:mysql://192.168.31.100:3306/spring_cloud_alibaba?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
#    username: root
#    password: mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
## 设置 feign 客户端超时时间(OpenFeign 默认支持 Ribbon)
#ribbon:
#  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#  read-timeout: 2000
#  # 指的是建立连接后从服务器读取到可用资源所用的时间
#  connect-timeout: 2000
#
#feign:
#  client:
#    config:
#      Product:
#        loggerLevel: full
#      Order:
#        loggerLevel: full
## Feign日志只会对日志级别为debug的做出响应
#logging:
#  level:
#    com.example.order.ms.ProductFeignService: debug
#    com.example.order.ms.OrderFeignService: debug