#server:
#  port: 9006
#  servlet:
#    context-path: /demo_spring_cloud_alibaba/order
#spring:
#  application:
#    name: Order
#  profiles:
#    active: dev
#mybatis-plus:
#  mapper-location: classpath:mapper/*.xml
